### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by admalledd** [alexanderjulo/wiki#39]
My current site already has a collection of apps using python3.4 flask and such.

How does it look to port this to python3?

**Comment by alexanderjulo** [comment]
I am currently re-writing the whole project so that we can also support python3. It is currently not perfect but it is getting much better and I am currently adding tests so we can ensure compatibility for the future. In the meantime I will be closing this issue and the PR. Please open new issues if you encounter any issues. Thanks for your support!
